### ISSUE TITLE
Differences between T-mode and S-mode in EOFs

### ISSUE THREAD

**Issue by GIRIJA-KALYANI** [nicrie/xeofs#31]
Dear Team xeofs,
I'm using xeofs for eof analysis.
I accidentally used it along spatial dimensions, but the API description says the traditional way is to use it along Time dimensions.
![image](https://user-images.githubusercontent.com/7091088/198088977-5b68f2b9-b8dd-4241-bb3b-fe196b796030.png)

I got more information on this from: http://dx.doi.org/10.1016/j.rse.2014.03.015
However, now I'm a bit confused as the paper talks about 4 modes as extended EOFs. In S-mode, sS-mode and tS-mode, and T-mode: sT-mode and tT-mode. I just want to know the t-mode here refers to which of the two modes: tS or sT?

**Comment by nicrie** [comment]
Hi Girija-Kalyani,
The topic can indeed be a bit confusing, I'll try to make it short:

* **PCA** decomposes a 2D data set X (`samples` x `features`). Sample and feature are generic, so they can contain whatever you want. It is important to understand that PCA reduces the dimension of the `features` by grouping the features together in such a way that the correlation/covariance is maximised along the `sample` dimension. 

* **Multivariate PCA** combines different data sets X1, X2, ... by concatenating the data sets X = [X1 | X2 | ...] and then performing PCA of X. The concatenation is usually done along the `feature` dimension (so that X1, X2, etc. must have the same number of samples), but theoretically the concatenation can also be done along the `sample` dimension (as long as X1, X2, has the same number of features).

* Now to climate science: Here we mostly deal with 3D datasets (`time`, `lat`, `lon`) and depending on which dimension you reduce, different names are given:
* **S-mode**: Reduce the spatial dimension (`sample`=`time`, `feature`=(`lat`, `lon`)); helps you e.g. with the discovery of teleconnections or generally with the question: which gridpoints behave similarly and can be grouped accordingly?
* **T-mode**: Reduce the temporal dimension (`sample`=(`lat`, `lon`), `feature`=`time`); helps you e.g. with the representation of weather regimes or in general with the question: which time steps (maps) have a similar spatial structure and can be grouped accordingly?

For the difference between S- and T-mode and which implications it has for the geoscientific context, this paper by [Compagnucci and Richman](https://onlinelibrary.wiley.com/doi/abs/10.1002/joc.1574) can be very enlightening. By the way, there are also O, P, Q and R modes ;-) 

* **Extended EOF**: Is nothing else than multivariate PCA, where the original data set X (e.g. a variable like SST) is concatenated with different time lags t_i, so that X_final = [X_t_0 | X_t_1 | ... | X_t_i) can be analysed using PCA. 

In the paper you cite, the authors Neeti and Eastman now investigate what implications the different combinations of S-mode, T-mode and concatenation (along feature or sample dimension) have on interpretation in the geoscientific context.

Now that the nomenclature is hopefully clearer, I can also answer your question easily ^^
* **S-mode**: `dim=['time']`
* **T-mode**: `dim=['lat', 'lon']`
* **Extended EOF**: Not directly implemented but you could do something easy as `xe.xarray.EOF([X1, X1.shift({'time': 1}), X1.shift({'time': 2})., ...], ...)`
* **sS-mode**: `xe.xarray.EOF([X1, X2], dim=('lat', 'lon'))`
* **tT-mode**: `xe.xarray.EOF([X1, X2], dim=('time'))`
* **tS-mode**: xeofs always concatenates along feature dimension, i.e. this case is not possible with xeofs
* **sT-mode**: same as for tS-mode

Hope that clears things up!

**Comment by GIRIJA-KALYANI** [comment]
It is indeed clear and I'm extremely grateful for the precise explanation. 
Since yesterday I'm looking at multiple papers to understand the stuff and things are getting only complicated as I get through deeply. So, the extended EOFs are similar to this? 
(https://xeofs.readthedocs.io/en/latest/auto_examples/1eof/plot_multivariate-eof.html#sphx-glr-auto-examples-1eof-plot-multivariate-eof-py). 
So, 'Multivariate PCA' combines different data sets and for extended EOFs, it is just one dataset at different time lags ?
I might test this and get back if I have any questions.

Also, I'm exploring what else I can do with XEOFs - and came across eof_as_correlation : 
![image](https://user-images.githubusercontent.com/7091088/198330415-5bc36f42-5735-4850-869c-d29e85aee11d.png)
Although I'm aware that EOFs are based on covariance matrices, what is eof_as_correlation? what are the resultant PCs correlated to? the original data?  

Many Many thanks for taking time to explain again

**Comment by GIRIJA-KALYANI** [comment]
It is indeed clear and I'm extremely grateful for the precise explanation. 
Since yesterday I'm looking at multiple papers to understand the stuff and things are getting only complicated as I get through deeply. So, the extended EOFs are similar to this? 
(https://xeofs.readthedocs.io/en/latest/auto_examples/1eof/plot_multivariate-eof.html#sphx-glr-auto-examples-1eof-plot-multivariate-eof-py). 
So, 'Multivariate PCA' combines different data sets and for extended EOFs, it is just one dataset at different time lags ?
I might test this and get back if I have any questions.

Also, I'm exploring what else I can do with XEOFs - and came across eof_as_correlation : 
![image](https://user-images.githubusercontent.com/7091088/198330415-5bc36f42-5735-4850-869c-d29e85aee11d.png)
Although I'm aware that EOFs are based on covariance matrices, what is eof_as_correlation? what are the resultant PCs correlated to? the original data?  

Many Many thanks for taking time to explain again

**Comment by nicrie** [comment]
> So, 'Multivariate PCA' combines different data sets and for extended EOFs, it is just one dataset at different time lags ?

Yes, that's correct!

> Although I'm aware that EOFs are based on covariance matrices, what is eof_as_correlation? what are the resultant PCs correlated to? the original data?

1. EOFs can be based on the covariance **or** correlation matrix depending on whether you standardize you data or not. 
2. Yes, correct! `eofs_as_correlation` calculates the correlation between the original data X and the individual PCs, i.e. corr(X, PCs). The result is a correlation map per mode. Typically the first modes have rather high correlation which then drops for higher modes.

Glad it helps! :)

**Comment by GIRIJA-KALYANI** [comment]
Great!!! Very Clear.

Thanks a lot again.

Cheers 
Girija
