### ISSUE TITLE
Additional Information on the usage of package:xEOFs

### ISSUE THREAD

**Issue by GIRIJA-KALYANI** [nicrie/xeofs#33]
Hello Team xEOFs,
Can you please help me with the following :
1) How do I set the PC scaling to 1 and 2 (square root of singular values and singular values respectively) from the default o (orthonormal)?
2) What if I want explained variance and SCFs alongside the plot of each mode? 
I'm able to view them individually this way: 
![image](https://user-images.githubusercontent.com/7091088/201413676-4ed72c8f-f2e2-400e-b557-bcfebcf99573.png)
but I want them embedded in the plot.
3) Plus, how do I project new data onto singular vectors? I  came across this in API : **project_onto_right_singular_vectors(Y: Optional[Union[DataArray, List[DataArray]]] = None, scaling: int = 0) → DataArray**, what is the right way to use it?
4) Also, is there a way we can find lagged relationships/covariances using xeofs?
5) Also, how can we try CCA with xeofs?

I'm trying to find answers in API - but, am unable to. 
Please assist me with relevant material at least to proceed further,.
Thank in advance
Cheers

**Comment by nicrie** [comment]
Hi Girija-Kalyani,
1. This can be achieved by calling the PCs with the corresponding parameter e.g. `pca.pcs(scaling=1)`, same applies for EOFs.
2. This sounds to me more like a question on how to use matpotlib's `twinx`, e.g. check examples [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.twinx.html).
3. Yes, that's the correct method if you're performing a MCA. Just use the new data `Ynew` which should be a `xr.DataArray` of the same feature dimensions (i.e. mostly the spatial dimensions `lon`x`lat`) of the original left DataArray (X) and another sample dimension (mostly `time`) of arbitrary length. Then `mca.project_onto_right_singular_vectors(Ynew)` will compute the projections onto the right singular vector. Similarly, you can get the projections onto the left singlar vectors by the corresponding call `mca.project_onto_right_singular_vectors(Xnew)` 
4. An easy way would be to you use 2 time-lagged DataArrays as the input data for MCA, so that you have a predictor X and a predictant Y. However, this requires a priori knowledge of the time lag. For a more general approach identifying lagging signals you could check out complex decomposition approaches, some early works by [Horel 1984](https://journals.ametsoc.org/doi/abs/10.1175/1520-0450(1984)023%3C1660%3ACPCATA%3E2.0.CO%3B2) and more recent adaptations and extension by [Bueso et al](http://arxiv.org/abs/2002.04539) 2020 or [Guilloteau et al](http://arxiv.org/abs/2004.11411). 2020. I tried myself on this one specifically for complex [MCA](https://journals.ametsoc.org/view/journals/clim/34/24/JCLI-D-21-0244.1.xml), but it's a tricky topic to be honest and I'd rather start with a more basic approach (i.e. Extended EOF analysis or extended MCA using time-shifted predictor/predictant pairs). In any case, none of these techniques are included in `xeofs` so far, but it's definitely on my agenda! 
5. Unfortunately CCA is not implemented yet, but it's very high on my agenda as well!

**Comment by GIRIJA-KALYANI** [comment]
Many Appreciations for the response @nicrie  Niclas.
All of the questions are adequately addressed and thanks for the links on lagged relationships. I really liked the honest suggestion of starting with basic approaches. Doing that!!
Regards
