### ISSUE TITLE
Maximum Covariance Analysis is slower than one in the nicrie/xmca

### ISSUE THREAD

**Issue by shenyulu** [nicrie/xeofs#77]
Hello, I recently migrated the dependency library from `nicrie/xmca` to `nicrie/xeofs`, it seems that the speed of SVD decomposition has slowed down significantly. I found that the calculation function was transferred from `np.linalg.svd` to `sklearn.utils.extmath.randomized_svd`. I personally don’t know the reason for this replacement. Maybe there are some tricks to speed up the calculation?

minimal reproducible code (xmca==1.4.2, xeofs==1.0.5)

```python
import pooch 
pooch.retrieve(url="https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2/sst.mnmean.nc", known_hash=None, path ='.', fname='sst.mnmean.nc')
pooch.retrieve(url="https://downloads.psl.noaa.gov/Datasets/cmap/enh/precip.mon.mean.nc", known_hash=None, path ='.', fname='precip.mon.mean.nc')

data_input1 = xr.open_dataset('sst.mnmean.nc', chunks = 'auto').sst.sel(time = slice('1982-01-01', '2022-12-31'))
data_input2 = xr.open_dataset('precip.mon.mean.nc', chunks = 'auto').precip.sel(time = slice('1982-01-01', '2022-12-31'))
```

Calculates very fast on my computer, about 5 seconds (It has nothing to do with the use of dask after the data chunk)

```python
from xmca.xarray import xMCA

mca = xMCA(data_input1, data_input2)
mca.normalize()
mca.apply_coslat()
mca.solve(complexify=False)
```

But the calculation using `xeof` is very slow, and the result cannot be obtained in a few minutes

```python
from xeofs.models import MCA

model = MCA(n_modes = 5, standardize = False, use_coslat = True)
model.fit(data_input1, data_input2, dim = 'time')
```

**Comment by nicrie** [comment]
Great catch! You're correct, the issue you mentioned isn't related to `dask`. The cross-covariance from your data has dimensions `64800 x 10368`, which is near the maximum size solvable on a typical laptop using `np.linalg.svd`. For such large matrices, the randomized SVD from `sklearn` is recommended as it's faster. That's why it is the default option in `xeofs`.

However, `xmca` is still able to handle the datasets with `np.linalg.svd`, because it first conducts standard PCA on each data set prior to computing the cross-covariance. Given that your data sets have `492` time steps, they can be fully represented by `492` PCs. Thus, when performing MCA in this reduced PCA space, the SVD solution should be swift.

Currently, `xeofs` doesn't offer this PCA preprocessing. But, good news – it's present in the development branch. If you need it urgently, install the development version:

```
pip install git+https://github.com/nicrie/xeofs.git@develop
```

The development version then allows you to specify the number of PCA modes. Since in your case the rank of the input matrices are 492, you can easily provide all PC modes so you don't loose any information by using the PCA solutions as input for MCA. In the development version you would specify it like this:

```py
model = MCA(n_modes=5, standardize=False, use_coslat=True, n_pca_modes=492),
model.fit(data_input1, data_input2, dim='time')
```


Otherwise, if you don't mind waiting a couple of days more, I'll be releasing a new version with this feature soon.

**Comment by shenyulu** [comment]
> Yeah, just what I wanted, thank you. I found this trick, looking forward to the new release

**Comment by nicrie** [comment]
this feature is now available in the new release `v.1.1.0`  (see #80 )
