### ISSUE TITLE
Complex MCA & CCA related

### ISSUE THREAD

**Issue by gkb999** [nicrie/xeofs#78]
Greetings Niclas @nicrie ,
I was going through this paper of yours "https://arxiv.org/pdf/2105.04618.pdf" -> how do you perform complex rotated mca?
Like from xeofs, the routine MCA code does:
```python
mca = MCA(
    X, Y,
    n_modes=20,
    dim='time',
    norm=False,
    weights_X='coslat',
    weights_Y='coslat'
)
```
 
I'm going through this documentation (link: https://xeofs.readthedocs.io/en/latest/_autosummary/xeofs.models.ComplexMCA.html), yet, I don't understand how to call Complex MCA. 
I tried "cmca = ComplexMCA() " this way, but it says it isn't defined.

Also, I see an upgrade on CCA addition, can you please direct to the documentation too?

Lastly, my data is a daily one, not for all the months, just 3 months for year (continuing for 20 yrs).
When I plot mca time series, I get something like:
![111](https://github.com/nicrie/xeofs/assets/7091088/a3b40bbb-f9ed-43c0-b501-7a965bfda8c4)
whereas, I wnated a continous one plotted on years based on my data like:
![222](https://github.com/nicrie/xeofs/assets/7091088/088029ea-c1b0-4a09-89d8-a1271bf6f219)

Any assistance and support will be greatly appreciated

**Comment by gkb999** [comment]
Also, my the time series in my data isn't continous.
I picked a few months (say, Jun, Jul, Aug) for each year to see seasonal coherences.
How do I look for lagged connections here, as if i shift the time series, I can mistakenly use previous year's data with another years
Eg: 2005 Aug with 2006 June -> which makes no sense at all.

Is there a way to handle such cases in XEOFs?

Many thanks in advance

**Comment by nicrie** [comment]
Hi @gkb999 I'm currently on a mission I can only respond briefly:

**1. Complex MCA**

```py
import xeofs as xe
cmca = xe.models.ComplexMCA(n_modes=10)
cmca.fit(X, Y)
left_patterns, right_patterns = cmca.components()
``` 

**2. Complex rotated MCA**
```py
rot = xe.models.ComplexMCARotator(n_modes=5)
rot.fit(cmca)
left_rotated_patterns, right_rotated_patterns = rot.components()
``` 

If these methods are not available to use please check the `xeofs` version and in case upgrade to the most recent one (`v1.0.5`)

**3. CCA**
Not yet available, but in process ;-)

**4. Plots**
Did you try to drop the `NaN`s? I'm guessing that's what your looking for, although it's not really related to `xeofs` ;) 
Like e.g. `data.dropna('time')` ?

**5. Lagged MCA**
I think you can use daily sampled data (even if 8 months are filled with `NaN` and then shift the data. Finally you can drop all `NaN`s, so that you retain your original months with data only. The shift that you applied to your data should then be reflected as additional `NaN`s in your 4 target months.

**Comment by gkb999** [comment]
Thanks a lot for the brief answers.
All the 4 are fine.
5th one is a bit confusing, as filling data with NaN, won't accept for either MCA/EOF using our xeofs package right?

**Comment by nicrie** [comment]
Yes your correct about the input for xeofs, you'll have to drop the NaN beforehand via .e.g. dropna.('time')

Say  you have June to August and you want to shift by 7 days, then:
1. Upsampling to daily data filling missing values with Nan
2. Shift data by 7 days,I.e. the first week of june will be NAN now
3. Drop nan's. Your final data will be the last 3 weeks in june + july/august

**Comment by nicrie** [comment]
Closing - feel free to reopen.
