### ISSUE TITLE
support for GWPCA

### ISSUE THREAD

**Issue by NILICK** [nicrie/xeofs#84]
I would like to utilize xeofs in my research due to its compatibility with xarray datasets/data arrays, which makes working with them convenient. I am interested in determining if xeofs supports the calculation of Geographically Weighted PCA (GWPCA). Is it possible to do it?

**Comment by nicrie** [comment]
hey @NILICK GWPCA is not available in `xeofs`, however, it seems to be a great fit for this package. I don't know when I will have some time to implement it, but I'll put it on the to do list!

**Comment by nicrie** [comment]
alright! :) just wanted to be sure what the requirements for a GWPCA class would or could be. I mostly work with regular lon lat grids, similar to what you have. But I guess that GWPCA could also find applications in settings where you have irregular lon lat coordinates or even X and Y dimensions in meters. If you like to share a small sample of your data, that could indeed help! :+1:

**Comment by nicrie** [comment]
hey no worries! I guess [WeTransfer](https://wetransfer.com/) is the easiest?

**Comment by nicrie** [comment]
you can send it either to [me](mailto:niclasrieger@gmail.com) or post the WT link in that thread instead

**Comment by nicrie** [comment]
version 1.2.0 has been released, which offers basic support for GWPCA ([here's an example](https://xeofs.readthedocs.io/en/develop/auto_examples/1eof/plot_gwpca.html#sphx-glr-auto-examples-1eof-plot-gwpca-py) to get you started). I describe it as "basic" because, while the implementation is optimized for CPU, it lacks GPU support. Given that GWPCA is computationally intensive, I believe the current implementation is best suited for small data sets. I've made several attempts to enhance its performance, but ultimately, I think GPU support will be essential for processing typical-sized climate data. Unfortunately, I won't have the time to delve into that in the near future.
