### ISSUE TITLE
Add serialization methods

### ISSUE THREAD

**Issue by slevang** [nicrie/xeofs#95]
One thing missing from most EOF libraries is a method to quickly serialize/deserialize the solver to disk. This becomes necessary for any sort of real-time use case, where you may want to take new data and project onto the components using `transform()` with a pre-computed solver.

What do you thinking about adding this to `xeofs`? One can of course use `pickle` to do this, but that quickly leads to compatibility issues with new versions. It should be straightforward to dump to netcdf or zarr since we just need to save a few arrays and the essential attributes used to instantiate the solver. Perhaps a `.save()` method on the models, plus `.load()` as a `classmethod` or some other loading utility function?

**Comment by nicrie** [comment]
Certainly useful! I also lean towards using `.save()` / `.load()` instead of a utility function, though it's just a personal preference without a concrete reason ;) Currently, all required `DataArrays` reside in `self.data`, which functions like an enhanced dictionary, so we could iterate through them. Any ideas how we can efficiently store such a list of `DataArrays`?

A challenge arises when the model needs the original input data. Right now, all `xeofs` models store this input data in `self.data`. However, if the data is in a `Dask` array form, it's never computed. Take MCA for instance, where you need the original input to calculate the homogeneous/heterogeneous patterns. If we're dealing with large-scale `Dask` array data, we wouldn't want to save it to disk twice. This means that saving and then loading a model might limit some functions. Despite this, I see it as a manageable issue, especially given the advantage of applying transformations on new data.

**Comment by slevang** [comment]
Ok nice, I hadn't looked at the `DataContainer` class yet. Caveat all of this that I haven't even used the 1.x of this library yet haha.

`DataContainer` stores `DataArray`'s, so I think the easiest thing would be to just do an `xr.merge(self.data.values())` to get a `Dataset`, then offer `.save(path=..., format={'netcdf', 'zarr', ... etc})` with standard xarray io methods. Then `.load(path=...)` should be able to rebuild `self.data` by looping through the loaded `ds.data_vars`. We would also need to save and load `self._params`, which could be set as dataset level attributes on the serialized object.

Needing to attach the original data is something I hadn't thought of and does present some challenges. Fortunately you already have the `_allow_compute` property which describes things we probably don't want to save, although this could be configurable. If we have a large dataset, and don't want to duplicate it, the `.load()` method could throw a warning that `input_data` wasn't loaded and provide the user a straightforward way to set this with e.g. `.load_data()` or something.

**Comment by nicrie** [comment]
Sounds like a good idea! Not sure when I'll find the time to implement it, but it definitely makes sense :) If you wanna give it a shot in the meantime, awesome!

**Comment by slevang** [comment]
Might be a few weeks but I can probably give it a shot.

**Comment by slevang** [comment]
I got a start on this yesterday. Handling the `DataContainer` objects is straightforward, with the caveat of what to do with the `input_data` objects.

Where I ran into trouble is handling the `preprocessor`, which is quite a bit more complicated. We need this to be fully instantiated as well to be able to do:
```python
eof = EOF.load('eof.nc')
eof.transform(X_new)
```

At first I thought to have an attribute on each `transformer` describing the needed attributes required to successfully deserialize from disk in order to run `transform` and `inverse_transform`, and also attach these to the saved version. It isn't straightforward to reinstantiate these objects though, because all of the transformers aren't created until running `Preprocessor.fit()`, and some properties of the transformers are set by properties of `X` in that method. I think it can be done but may require a some restructuring.

The other options I thought of are:

1. make it mandatory to attach the original dataset, either via serializing with the fit model, or a secondary method to point directly to source (e.g. `load_data()`). This is a fairly annoying limitation though for models that don't require the original data for anything else
2. save some minimal dummy version of the original data with the fit model

Either one allowing us to run `Preprocessor.fit()` to set up the preprocessor when loading the model. We would still want to save and set some properties like the `mean_`/`std_`/`weights_` of the `Scaler` object to get round-tripped results.

**Comment by nicrie** [comment]
Cool, thanks Sam for diving into that! Ideally, I think we’d like to initialize the `Preprocessor` with the model right from the start. The only thing stopping us is the `Stacker`, which depending on the input data, is either a `DataArrayStacker` or a `DataSetStacker`, which we only know at the time of fitting.

Regarding the last two options:
1. I agree. Additionally, it could lead to unnecessary complications if, for whatever reason, the original data are no longer accessible (e.g., because they are located on a cluster).
2. I’m not sure to what extent we can "boil down" the original data to some dummy data. For the `MultiIndexConverter` as well as the `Stacker`, we would need all coordinates of the original dataset, meaning just a sample of the dataset is not sufficient. My feeling right now is that, ultimately, we would be back to the full original dataset.

On the other hand, we could apply your original approach to the individual transformers, meaning each of the 6 individual transformers gets a `.save` and `.load` method. We would only have to serialize the following information:

1. All parameters necessary for the initialization of the transformer -> granted by the `.get_params()` method inherited from sklearn's `BaseEstimator`.
2. All other attributes defined in `__init__` and `fit`. Mostly, these are various strs, tuples, or dicts, (does json make sense for this?) The exception to this is the `MultiIndexConverter` and `Stacker`, which both store `xr.Coordinates` (I’m currently not sure about the cleverest way to serialize those), and the `Scaler`, which requires `xr.DataArrays`/`Datasets` for `mean_` etc.

Right now, I’m leaning towards this last option here. It seems cleaner and less prone to problems in the long run. But surely, I’ve overlooked one or another hidden mine along the way ;)

**Comment by slevang** [comment]
Yeah agree, saving the necessary attributes and loading/instantiating everything in one go is best.

The `stacker` depending on `X` does seem tricky. I haven't looked at it in detail, do you think it would be straightforward to create  a single `Stacker` type that handles both DataArray or Dataset seamlessly?

If we don't care about the preprocessor having standalone save/load capability, it would keep the file package a bit neater to pass the necessary preprocessor attributes back to `model.save()` and merge, then separate out back on load. Separate files would work fine too. json could work but since we do have some coordinates and DataArrays, it may be easier to push everything into netcdf/zarr.

**Comment by nicrie** [comment]
Now that you mention it... there were reasons back in the days of version `0.x.y` to have subclasses for every input type. But now, the only remnant of that approach is the `Stacker` class. I think it's straightforward to merge the `DataArrayStacker` and `DataSetStacker`. Even though the final `Stacker` class will be a bit bloated, it seems worth it given the advantages.

I'll try to implement that the coming days

**Comment by nicrie** [comment]
I've refactored the code ([b18c3e0](https://github.com/nicrie/xeofs/commit/b18c3e077d0225d393fddce8eff9b535c0f3312b)). Now, the `Stacker` is compatible with both `DataArray` and `Dataset`. Additionally, the `Preprocessor` is initialized right at the beginning.

**Comment by slevang** [comment]
Awesome, looks good. I'll merge this into my work so far and get a PR up in the next day or two.
